name: Cache Maven

# change this once on main branch to workflow_dispatch
on: pull_request

jobs:
  cache:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25
          cache: maven
      - uses: taiki-e/install-action@just

      # - name: Cache test dependencies
      #   continue-on-error: true
      #   run: just test

      # - name: Cache lint dependencies
      #   continue-on-error: true
      #   run: just check

      # - name: Cache ddl check dependencies
      #   continue-on-error: true
      #   run: just compile _gen-classpath

      - name: Just CI value
        continue-on-error: true
        run: just temp
